# Generated by Django 5.2.12 on 2026-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("service_type", models.CharField(max_length=100)),
                ("project_description", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_ar", models.CharField(max_length=100)),
                ("label_en", models.CharField(blank=True, max_length=100)),
                ("href", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading_ar",
                    models.CharField(
                        default="نبتكر حلولاً ذكية تُشكّل المستقبل", max_length=300
                    ),
                ),
                ("heading_en", models.CharField(blank=True, max_length=300)),
                (
                    "subheading_ar",
                    models.TextField(
                        default="نواس الابتكارية — شريكك الموثوق في المملكة العربية السعودية للتحول الرقمي وتطوير حلول الذكاء الاصطناعي المتطورة."
                    ),
                ),
                ("subheading_en", models.TextField(blank=True)),
                (
                    "cta_primary_text_ar",
                    models.CharField(default="اكتشف خدماتنا", max_length=100),
                ),
                ("cta_primary_text_en", models.CharField(blank=True, max_length=100)),
                (
                    "cta_primary_link",
                    models.CharField(default="#services", max_length=200),
                ),
                (
                    "cta_secondary_text_ar",
                    models.CharField(default="تواصل معنا", max_length=100),
                ),
                ("cta_secondary_text_en", models.CharField(blank=True, max_length=100)),
                (
                    "cta_secondary_link",
                    models.CharField(default="#contact", max_length=200),
                ),
                ("background_image", models.ImageField(blank=True, upload_to="hero/")),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="LearnCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome class, e.g. 'fas fa-brain'",
                        max_length=100,
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_ar", models.CharField(max_length=100)),
                ("label_en", models.CharField(blank=True, max_length=100)),
                ("href", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                ("features_ar", models.TextField(help_text="One feature per line")),
                (
                    "features_en",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
                ("link", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SectionHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("learn", "Learn"),
                            ("services", "Services"),
                            ("products", "Products"),
                            ("contact", "Contact"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("subtitle_ar", models.CharField(max_length=300)),
                ("subtitle_en", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Font Awesome class, e.g. 'fas fa-code'",
                        max_length=100,
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("description_ar", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name_ar",
                    models.CharField(default="نواس الابتكارية", max_length=200),
                ),
                (
                    "site_name_en",
                    models.CharField(
                        blank=True, default="Nuwas Innovative", max_length=200
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                ("email", models.EmailField(default="info@nuwas.sa", max_length=254)),
                ("phone", models.CharField(default="+966 500 000 000", max_length=30)),
                (
                    "address_ar",
                    models.CharField(default="جدة - الرياض، السعودية", max_length=300),
                ),
                ("address_en", models.CharField(blank=True, max_length=300)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "copyright_text_ar",
                    models.CharField(
                        default="جميع الحقوق محفوظة © 2026 نواس الابتكارية لتقنية المعلومات",
                        max_length=300,
                    ),
                ),
                ("copyright_text_en", models.CharField(blank=True, max_length=300)),
                (
                    "footer_description_ar",
                    models.TextField(
                        blank=True,
                        default="شركة رائدة في تقديم الحلول البرمجية والذكاء الاصطناعي، نساهم في تحقيق رؤية المملكة 2030 من خلال الابتكار التقني.",
                    ),
                ),
                ("footer_description_en", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="StatItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("label_ar", models.CharField(max_length=100)),
                ("label_en", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
