# Generated by Django 5.2.12 on 2026-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(blank=True, upload_to="videos/")),
                (
                    "phrase_ar",
                    models.CharField(
                        default="نبتكر حلولاً ذكية تُشكّل المستقبل", max_length=300
                    ),
                ),
                ("phrase_en", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Video Banner",
                "verbose_name_plural": "Video Banner",
            },
        ),
    ]
