# Generated by Django 5.2.12 on 2026-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_videobanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="logo",
            field=models.ImageField(blank=True, upload_to="products/"),
        ),
    ]
