# Generated by Django 5.2.12 on 2026-04-02 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="مفتاح API من Anthropic", max_length=200
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("claude-sonnet-4-20250514", "Claude Sonnet 4"),
                            ("claude-opus-4-20250514", "Claude Opus 4"),
                        ],
                        default="claude-sonnet-4-20250514",
                        help_text="نموذج الذكاء الاصطناعي المستخدم",
                        max_length=100,
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=8192)),
                ("temperature", models.FloatField(default=0.7)),
            ],
            options={
                "verbose_name": "AI Configuration",
                "verbose_name_plural": "AI Configuration",
            },
        ),
        migrations.CreateModel(
            name="ProposalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="رقم الجوال")),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الشركة/المؤسسة"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("mobile_app", "تطبيق جوال"),
                            ("web_platform", "منصة ويب"),
                            ("ai_system", "نظام ذكاء اصطناعي"),
                            ("digital_transformation", "تحول رقمي"),
                            ("other", "أخرى"),
                        ],
                        max_length=50,
                        verbose_name="نوع المشروع",
                    ),
                ),
                (
                    "project_description",
                    models.TextField(verbose_name="وصف فكرة المشروع"),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_50k", "أقل من 50,000 ريال"),
                            ("50k_150k", "50,000 - 150,000 ريال"),
                            ("150k_500k", "150,000 - 500,000 ريال"),
                            ("over_500k", "أكثر من 500,000 ريال"),
                            ("undecided", "لم يتم التحديد"),
                        ],
                        default="undecided",
                        max_length=50,
                        verbose_name="نطاق الميزانية",
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("1_3_months", "1-3 أشهر"),
                            ("3_6_months", "3-6 أشهر"),
                            ("6_12_months", "6-12 شهر"),
                            ("flexible", "مرن"),
                        ],
                        default="flexible",
                        max_length=50,
                        verbose_name="الجدول الزمني",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد — بانتظار المراجعة"),
                            ("reviewed", "تمت المراجعة"),
                            ("generating", "جاري التوليد بالذكاء الاصطناعي"),
                            ("generated", "تم التوليد — بانتظار موافقة الإدارة"),
                            ("approved", "معتمد — جاهز للإرسال"),
                            ("sent", "تم الإرسال للعميل"),
                            ("completed", "العميل أكمل الاستمارة"),
                            ("closed", "مغلق"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="ملاحظات داخلية للإدارة — لا تظهر للعميل",
                        verbose_name="ملاحظات الإدارة",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب عرض سعر",
                "verbose_name_plural": "طلبات عروض الأسعار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedQuestionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("token_expires_at", models.DateTimeField()),
                (
                    "ai_model",
                    models.CharField(
                        default="claude-sonnet-4-20250514", max_length=100
                    ),
                ),
                ("ai_prompt_used", models.TextField(blank=True)),
                ("generated_html", models.TextField(blank=True)),
                ("generation_metadata", models.JSONField(blank=True, default=dict)),
                ("features", models.JSONField(blank=True, default=list)),
                ("total_features", models.IntegerField(default=0)),
                ("total_requirements", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة — بانتظار مراجعة الإدارة"),
                            ("approved", "معتمد — جاهز للإرسال"),
                            ("sent", "تم الإرسال للعميل"),
                            ("rejected", "مرفوض — يحتاج إعادة توليد"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "admin_feedback",
                    models.TextField(
                        blank=True, help_text="ملاحظات الإدارة على الاستمارة المولّدة"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_questionnaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="questionnaire.proposalrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "استمارة مولّدة",
                "verbose_name_plural": "الاستمارات المولّدة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("questionnaire_link", "رابط الاستمارة"),
                            ("reminder", "تذكير"),
                            ("thank_you", "شكر"),
                            ("admin_notification", "إشعار للإدارة"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "تم الإرسال"),
                            ("delivered", "تم التسليم"),
                            ("opened", "تم الفتح"),
                            ("bounced", "ارتداد"),
                            ("failed", "فشل"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="questionnaire.proposalrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل البريد",
                "verbose_name_plural": "سجلات البريد",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_requirements", models.JSONField(default=list)),
                ("na_requirements", models.JSONField(default=list)),
                ("sub_answers", models.JSONField(default=dict)),
                ("summary_snapshot", models.JSONField(default=dict)),
                ("respondent_name", models.CharField(max_length=200)),
                ("respondent_email", models.EmailField(max_length=254)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("completion_percentage", models.FloatField(default=0)),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="questionnaire.generatedquestionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "رد العميل",
                "verbose_name_plural": "ردود العملاء",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
